version: "3.8"
services:
  mc_server_new:
    image: itzg/minecraft-server:java17
    container_name: mc_1_20_1_modded
    # --- ЭТИ СТРОКИ ВКЛЮЧАЮТ КОНСОЛЬ ---
    tty: true
    stdin_open: true
    # -----------------------------------
    ports:
      - "25566:25565/tcp" # Основной порт для игры
      - "25566:25565/udp" # ПОРТ ДЛЯ МОНИТОРИНГА (Query)
      - "25576:25575/tcp" # RCON
      - "8100:8100" # <-- ДОБАВЛЯЕМ ПОРТ ДЛЯ BLUEMAP
    environment:
      EULA: "TRUE"
      VERSION: "1.20.1"
      TYPE: "FORGE"
      MEMORY: "4G" 
      ENABLE_RCON: "true"
      RCON_PASSWORD: "093b6d5e358d302933b7e326"
      # --- АВТОМАТИЧЕСКОЕ ВКЛЮЧЕНИЕ QUERY ---
      ENABLE_QUERY: "true"
      QUERY_PORT: "25565"
    volumes:
      - mc_data_1_20_1:/data
    restart: unless-stopped

volumes:
  mc_data_1_20_1:
  
